version: "3"

services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "mydatabase"
      MYSQL_ROOT_PASSWORD: "123123"
    volumes:
      - ./db/db-data:/var/lib/mysql
      - ./db/classicmodels.sql:/docker-entrypoint-initdb.d/classicmodels.sql
    ports:
      - 3306:3306
  backend-classic:
    build:
      context: .
    container_name: backend-classic
    restart: always
    depends_on:
      - db
    ports:
      - "4242:4242"

volumes:
  db-data:
