pipeline {
    agent any
    stages {
        stage('Build Docker image - backend') {
            steps {
                script {
                  dockerapp = docker.build("iagoabner/backend-classicmodels:${env.BUILD_ID}", "-f ../backend/dockerfile .")
                }
            }
        }
        stage('Build Docker image - frontend') {
            steps {
                script {
                  dockerapp = docker.build("iagoabner/frontend-classicmodels:${env.BUILD_ID}", "-f ../frontend/dockerfile .")
                }
            }
        }
    }
}
