version: "3"

services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "mydatabase"
      MYSQL_ROOT_PASSWORD: "123123"
    volumes:
      - ./db-data:/var/lib/mysql
      - ./mysqlsampledatabase.sql:/docker-entrypoint-initdb.d/mysqlsampledatabase.sql
    ports:
      - 3306:3306

volumes:
  db-data:
