- name: "Execute tasks for production environment"
  hosts: production
  become: yes
  roles:
    - install-docker
    - install-k8s
    # - install-jenkins
    - setup-applications
    - deploy-applications
